# Generated by Django 5.2.8 on 2026-03-17 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_track_name', models.CharField(blank=True, max_length=255, null=True)),
                ('base_track_artists', models.TextField(blank=True, default='')),
                ('base_track_cluster', models.IntegerField(blank=True, null=True)),
                ('used_feature', models.CharField(blank=True, max_length=100, null=True)),
                ('strategy_version', models.CharField(blank=True, default='v1', max_length=50, null=True)),
                ('dataset_version', models.CharField(blank=True, default='tracks_csv_v1', max_length=100, null=True)),
                ('algorithm', models.CharField(blank=True, default='content_based_cluster_filtering', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_recommendation_batches', to='api.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_list', models.PositiveSmallIntegerField()),
                ('list_type', models.CharField(choices=[('listRandom', 'Lista Aleatória'), ('listVariableBased', 'Lista Baseada em Variável')], max_length=30)),
                ('rating', models.PositiveSmallIntegerField()),
                ('base_metric', models.CharField(blank=True, max_length=100, null=True)),
                ('track_cluster', models.IntegerField(blank=True, null=True)),
                ('recommended_track_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_track_artists', models.TextField(blank=True, default='')),
                ('strategy_version', models.CharField(blank=True, default='v1', max_length=50, null=True)),
                ('dataset_version', models.CharField(blank=True, default='tracks_csv_v1', max_length=100, null=True)),
                ('algorithm', models.CharField(blank=True, default='content_based_cluster_filtering', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_track_evaluations', to='api.track')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.recommendationbatch')),
                ('recommended_track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_evaluations', to='api.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch_id', 'list_type', 'order_in_list'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'list_type', 'order_in_list'), name='unique_position_per_list_in_batch')],
            },
        ),
    ]
