# Generated by Django 5.2.8 on 2026-03-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recommendationbatch_recommendationevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationbatch',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='recommendationevaluation',
            name='algorithm',
        ),
        migrations.AddField(
            model_name='recommendationbatch',
            name='cluster_algorithm',
            field=models.CharField(blank=True, default='kmeans', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='cluster_algorithm',
            field=models.CharField(blank=True, default='kmeans', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationbatch',
            name='dataset_version',
            field=models.CharField(blank=True, default='spotify_1921_2020_524k_tracks.csv', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationbatch',
            name='strategy_version',
            field=models.CharField(blank=True, default='V1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationevaluation',
            name='dataset_version',
            field=models.CharField(blank=True, default='spotify_1921_2020_524k_tracks.csv', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationevaluation',
            name='strategy_version',
            field=models.CharField(blank=True, default='V1', max_length=50, null=True),
        ),
    ]
