# Generated by Django 5.2.7 on 2025-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
