# Generated by Django 5.2.8 on 2026-03-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_recommendationbatch_algorithm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationbatch',
            old_name='base_track_cluster',
            new_name='current_cluster',
        ),
        migrations.RenameField(
            model_name='recommendationevaluation',
            old_name='track_cluster',
            new_name='current_cluster',
        ),
        migrations.AddField(
            model_name='recommendationbatch',
            name='recommendation_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='recommendation_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
