# Generated by Django 5.2.8 on 2026-03-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_base_track_cluster_recommendationbatch_current_cluster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationbatch',
            name='current_cluster',
        ),
        migrations.RemoveField(
            model_name='recommendationevaluation',
            name='current_cluster',
        ),
    ]
