# Generated by Django 5.2.8 on 2026-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recommendationbatch_current_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.TextField(),
        ),
    ]
