# Generated by Django 5.2.8 on 2026-04-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationevaluation',
            name='language_influenced_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendationbatch',
            name='dataset_version',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationevaluation',
            name='dataset_version',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
