# Generated by Django 5.2.8 on 2026-04-29 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recommendationevaluation_language_influenced_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationbatch',
            name='client_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationbatch',
            name='client_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationbatch',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationbatch',
            name='experiment_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationbatch',
            name='session_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador público/analítico da sessão de avaliação.', null=True),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='base_track_cluster_at_recommendation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='base_track_feature_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='recommended_track_cluster_at_recommendation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='recommended_track_feature_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='spotify_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendationevaluation',
            name='was_preview_opened',
            field=models.BooleanField(default=False),
        ),
    ]
