# Generated by Django 5.2.8 on 2026-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recommendationbatch_client_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationevaluation',
            name='list_type',
            field=models.CharField(choices=[('randomList', 'Lista Aleatória'), ('greatestVariationList', 'Lista por Maior Variação'), ('furthestFromTheMedianList', 'Lista por Maior Distância da Mediana')], max_length=30),
        ),
    ]
